dataset:
  name: BLN600
  path: TMP/bln600

llm:
  use_llm: true
  model_name: "yandexgpt-5-lite-8b-instruct"
  provider: local
  host: http://localhost:1234/v1/chat/completions
  model: yandexgpt-5-lite-8b-instruct
  temperature: 0.2
  max_tokens: 4096
  top_p: 0.7
  top_k: 50
  strategy: correction

experiment:
  output_path: results/bln600_yandex_correction.yaml
  debug: true
