download_paths:
  raw_data_dir: "TMP/raw"

datasets:
  iam_url: "https://www.kaggle.com/datasets/naderabdalghani/iam-handwritten-forms-dataset"
  mlt19_url: "https://some-host/mlt19-data.zip"
  smile_twitter_url: "https://some-host/smile-twitter.zip"
  rusentiment_url: "https://github.com/strawberrypie/rusentiment/archive/refs/heads/master.zip"
  gutenberg_ids:
    - "12345"
    - "67890"
  gutenberg_base_url: "https://www.gutenberg.org/files/{book_id}/{book_id}-0.txt"

  lenta_input_path: "/path/to/lenta-ru-news.csv.gz"
  lenta_output_path: "TMP/raw/lenta/lenta_news.txt"
  lenta_limit: 10