dataset:
  name: "IAM"
  path: "TMP/iam"

ocr:
  engine: "Tesseract"
  params:
    config: "--psm 6 --oem 1"

llm:
  use_llm: true
  model_name: "llama-3.2-3b-instruct"
  temperature: 0.7

experiment:
  output_path: "results/llama_tesseract_results.yaml"
