dataset:
  name: "IAM"
  path: "TMP/iam"

ocr:
  engine: "EasyOCR"
  params:
    lang_list: ["en"]
    gpu: true

llm:
  use_llm: true
  model_name: "llama-3.2-3b-instruct"
  temperature: 0.7

experiment:
  output_path: "results/llama_easyocr_results.yaml"
