dataset:
  name: "IAM"
  path: "TMP/iam"

ocr:
  engine: "EasyOCR"
  params:
    lang_list: ["en"]
    # Если ваша версия EasyOCR >= 1.6, можно включить параметр paragraph=True
    # чтобы склеивать близкие блоки в абзацы
    paragraph: true
    gpu: true

llm:
  use_llm: true
  model_name: "mistral-7b-instruct-v0.3"
  temperature: 0.2
  top_p: 0.7
  top_k: 50

experiment:
  output_path: "results/mistral_easyocr.yaml"
  debug: false
