dataset:
  name: RETAS
  path: TMP/RETAS

llm:
  use_llm: true
  model_name: "mistral-7b-instruct-v0.3"
  provider: local
  host: http://localhost:1234/v1/chat/completions
  model: mistral-7b-instruct-v0.3
  temperature: 0.2
  max_tokens: 4096
  top_p: 0.7
  top_k: 50
  strategy: correction

experiment:
  output_path: results/retas_mistral_correction.yaml
  debug: true
